# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='PortTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=35, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('extrainfo', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('conf', models.CharField(blank=True, max_length=100, null=True)),
                ('id_domain', models.IntegerField(blank=True, null=True)),
                ('httptitle', models.TextField(blank=True, null=True)),
                ('cmstype', models.CharField(blank=True, max_length=100, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'port_table',
            },
        ),
        migrations.CreateModel(
            name='Subdomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(blank=True, max_length=150, null=True)),
                ('id_domain', models.IntegerField(blank=True, null=True)),
                ('cmstype', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'subdomains',
            },
        ),
        migrations.CreateModel(
            name='Vulns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('headers_string', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=15, null=True)),
                ('delta_time', models.CharField(blank=True, max_length=50, null=True)),
                ('vuln_name', models.CharField(blank=True, max_length=150, null=True)),
                ('severity', models.CharField(blank=True, max_length=30, null=True)),
                ('checks', models.CharField(blank=True, max_length=150, null=True)),
                ('proof', models.TextField(blank=True, null=True)),
                ('seed', models.TextField(blank=True, null=True)),
                ('id_domain', models.IntegerField(blank=True, null=True)),
                ('md5', models.CharField(max_length=32, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vulns',
            },
        ),
    ]
